
[project]
name = "testnet-faucet"
description = "A faucet to get testnet STX and tokens"
authors = []
telemetry = true
cache_dir = "./.cache"

[contracts.faucet]
path = "contracts/faucet.clar"
clarity_version = 2
epoch = 2.4

[repl]
clarity_wasm_mode = false
show_timings = false

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
